### ISSUE TITLE
 Evaluate and Select Optimal 3D Viewing Framework for Mobile

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2024group8#200]
### Issue Description

For the mobile application for our 3D design and modeling information exchange forum, a core requirement is to enable users to view and interact with 3D models directly within the app. Research and identify potential 3D viewing frameworks suitable for mobile platform (React Native).

Key considerations:
- Support for various 3D file formats
- User interaction capabilities (e.g., zooming, panning, rotating)

Make a recommendation for the most suitable framework, providing a justification for the choice.

### Issue Due Date

07/10/2024

### Reviewer

@oguzkagnici

### Revision Due Date

06/10/2024

**Comment by edonmez01** [comment]
I conducted some research regarding which 3D viewing framework to use in mobile.

I first investigated whether our first choice, [Online 3D Viewer](https://kovacsv.github.io/Online3DViewer/index.html), would be usable in our case. The biggest problem with this 3D viewing engine is that it doesn't support React Native directly, as it is developed as a React module. Despite this, it is theoretically possible to run this module in a React Native application by embedding it in an HTML section which is then fed to React Native as a WebView. However, while trying to do this, I encountered/foresaw three main problems:
- There are many possible compatibility issues that can arise while using a WebView to run a React module in a React Native app.
- Using a WebView makes debugging much harder than using native code.
- A lot of users report performance issues while using WebViews, which would be especially bad for us as loading 3D models is a relatively resource-heavy operation.

With these points in mind, I started to investigate alternative options, and stumbled upon the module [react-native-3d-module-view](https://github.com/BonnierNews/react-native-3d-model-view). First of all, as this module is developed directly for React Native, we won't have to deal with the three problems I listed above if we choose to use this module. The module is also fairly easy to use, as I was able to set up an example app within minutes after downloading it, using it to display [the 3D model of a hamburger](https://github.com/BonnierNews/react-native-3d-model-view/blob/master/example/obj/Hamburger.zip?raw=true):

<img width="512" alt="image" src="https://github.com/user-attachments/assets/3a147e08-a23f-454c-9d4d-ce35c264bbfc">

The only problem I ran into while developing this example app resulted from the fact that the module uses the old [Android Support Library](https://developer.android.com/topic/libraries/support-library), which is deprecated in favor of [AndroidX](https://developer.android.com/jetpack/androidx). This problem was solved easily, by only changing two lines in the module's source code.

I should also note that this module supports only 3 file extensions: .obj, .dae and .scn. However, I propose using this module for our mobile app as it seems very fitting for our purposes.

**Comment by AliAlperenSonmez** [comment]
> I conducted some research regarding which 3D viewing framework to use in mobile.
> 
> I first investigated whether our first choice, [Online 3D Viewer](https://kovacsv.github.io/Online3DViewer/index.html), would be usable in our case. The biggest problem with this 3D viewing engine is that it doesn't support React Native directly, as it is developed as a React module. Despite this, it is theoretically possible to run this module in a React Native application by embedding it in an HTML section which is then fed to React Native as a WebView. However, while trying to do this, I encountered/foresaw three main problems:
> 
> * There are many possible compatibility issues that can arise while using a WebView to run a React module in a React Native app.
> * Using a WebView makes debugging much harder than using native code.
> * A lot of users report performance issues while using WebViews, which would be especially bad for us as loading 3D models is a relatively resource-heavy operation.
> 
> With these points in mind, I started to investigate alternative options, and stumbled upon the module [react-native-3d-module-view](https://github.com/BonnierNews/react-native-3d-model-view). First of all, as this module is developed directly for React Native, we won't have to deal with the three problems I listed above if we choose to use this module. The module is also fairly easy to use, as I was able to set up an example app within minutes after downloading it, using it to display [the 3D model of a hamburger](https://github.com/BonnierNews/react-native-3d-model-view/blob/master/example/obj/Hamburger.zip?raw=true):
> 
> <img alt="image" width="512" src="https://private-user-images.githubusercontent.com/56600958/373959652-3a147e08-a23f-454c-9d4d-ce35c264bbfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzk4MjMsIm5iZiI6MTcyODM3OTUyMywicGF0aCI6Ii81NjYwMDk1OC8zNzM5NTk2NTItM2ExNDdlMDgtYTIzZi00NTRjLTlkNGQtY2UzNWMyNjRiYmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA5MjUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZjJhYmJkNWEyMzFkNGM1ZWY3MThmMzU2MzE5MzAzN2VlYzM5YjhjOTQyMjRhYzhhYTMzYjA5NzRmODllNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ooaRRJhekng_6cDR7tDfaXCeEvWRTDnf5sYgeJ46wgI">
> The only problem I ran into while developing this example app resulted from the fact that the module uses the old [Android Support Library](https://developer.android.com/topic/libraries/support-library), which is deprecated in favor of [AndroidX](https://developer.android.com/jetpack/androidx). This problem was solved easily, by only changing two lines in the module's source code.
> 
> I should also note that this module supports only 3 file extensions: .obj, .dae and .scn. However, I propose using this module for our mobile app as it seems very fitting for our purposes.

Thanks for your research and analysis. The recommended module appears to be valid.

**Comment by AliAlperenSonmez** [comment]
Seems valid.
