### ISSUE TITLE
Prepare requirements elicitation questions

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#46]
### Issue Description

A list of requirements elicitation questions have to be prepared that can be directed at the assistant (customer) to clarify some ambiguities about the project. The questions will be documented in the wiki.

### Issue Due Date

16/03/2024

### Reviewer

@daghanerdonmez @yektaercul 

### Revision Due Date

16/03/2024

**Comment by edonmez01** [comment]
Documented the requirements elicitation questions in a wiki page [here](https://github.com/bounswe/bounswe2024group8/wiki/Elicitation-Questions). Also added the link to the wiki sidebar.

**Comment by daghanerdonmez** [comment]
Seems pertinent with requirements and done according to what we've learned in class. Closing the issue.

**Comment by yektaercul** [comment]
I am reopening this issue since we need to apply some refactoring as the following:
1. Registration and Login (see requirements section 1.1.1)
Should the system remember that a user logged in for another time
Should the system be verified via email when trying to sign up with email
Can the user change its password in the future with email verification

2. Posts (see requirements sections 1.1.4 and 1.2.2)
2.2.1. and 2.2.2.
About moderators in communities. This is impossible in our system since the community creation is not possible. So there is no one to choose the moderators. 

Should ask:
Does the system will a have a functionality to search semanticly regarding the titles and tags of the post?

About 3.2.1. and 3.2.2.
Moderator specific question are again creates an hussle for us like the post deletion.

Generally Only the System-Admins and the owner of comment/post can delete their comment/post.

However We should ask:
Should we add a reporting system to mark posts or comments with malicious content.
And thus users can mark content that they find malicious.

4. Profile
Should the user accept the follower request or can one user follow anybody whenever he/she wants.

4.1. Great Idea

6.1. Should they get the content from the Wikidata API so that we utilize the api.

8.1. Can be a hussle for us. Should avoid.

**Comment by edonmez01** [comment]
Updated the page according to your feedback.

**Comment by yektaercul** [comment]
Added one more item to the Notifications. And other parts seems great and well-designed. Thanks for your work. Closing the issue.
